#############################################################################
# Makefile for building: tcp
# Generated by qmake (2.01a) (Qt 4.6.2) on: pt. mar 12 12:54:22 2010
# Project:  tcp.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tcp.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-klient \
		sub-serwer

klient//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) klient/ || $(MKDIR) klient/ 
	cd klient/ && $(QMAKE) /home/matthew/project/kurs-qt/7/tcp/klient/klient.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-klient-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) klient/ || $(MKDIR) klient/ 
	cd klient/ && $(QMAKE) /home/matthew/project/kurs-qt/7/tcp/klient/klient.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-klient: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE)
sub-klient-make_default-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) 
sub-klient-make_default: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) 
sub-klient-make_first-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) first
sub-klient-make_first: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) first
sub-klient-all-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) all
sub-klient-all: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) all
sub-klient-clean-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) clean
sub-klient-clean: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) clean
sub-klient-distclean-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) distclean
sub-klient-distclean: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) distclean
sub-klient-install_subtargets-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) install
sub-klient-install_subtargets: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) install
sub-klient-uninstall_subtargets-ordered: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-klient-uninstall_subtargets: klient//$(MAKEFILE) FORCE
	cd klient/ && $(MAKE) -f $(MAKEFILE) uninstall
serwer//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) serwer/ || $(MKDIR) serwer/ 
	cd serwer/ && $(QMAKE) /home/matthew/project/kurs-qt/7/tcp/serwer/serwer.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-serwer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) serwer/ || $(MKDIR) serwer/ 
	cd serwer/ && $(QMAKE) /home/matthew/project/kurs-qt/7/tcp/serwer/serwer.pro -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o $(MAKEFILE)
sub-serwer: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE)
sub-serwer-make_default-ordered: serwer//$(MAKEFILE) sub-klient-make_default-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) 
sub-serwer-make_default: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) 
sub-serwer-make_first-ordered: serwer//$(MAKEFILE) sub-klient-make_first-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) first
sub-serwer-make_first: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) first
sub-serwer-all-ordered: serwer//$(MAKEFILE) sub-klient-all-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) all
sub-serwer-all: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) all
sub-serwer-clean-ordered: serwer//$(MAKEFILE) sub-klient-clean-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) clean
sub-serwer-clean: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) clean
sub-serwer-distclean-ordered: serwer//$(MAKEFILE) sub-klient-distclean-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-serwer-distclean: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-serwer-install_subtargets-ordered: serwer//$(MAKEFILE) sub-klient-install_subtargets-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) install
sub-serwer-install_subtargets: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) install
sub-serwer-uninstall_subtargets-ordered: serwer//$(MAKEFILE) sub-klient-uninstall_subtargets-ordered  FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-serwer-uninstall_subtargets: serwer//$(MAKEFILE) FORCE
	cd serwer/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: tcp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tcp.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tcp.pro

qmake_all: sub-klient-qmake_all sub-serwer-qmake_all FORCE

make_default: sub-klient-make_default-ordered sub-serwer-make_default-ordered FORCE
make_first: sub-klient-make_first-ordered sub-serwer-make_first-ordered FORCE
all: sub-klient-all-ordered sub-serwer-all-ordered FORCE
clean: sub-klient-clean-ordered sub-serwer-clean-ordered FORCE
distclean: sub-klient-distclean-ordered sub-serwer-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-klient-install_subtargets-ordered sub-serwer-install_subtargets-ordered FORCE
uninstall_subtargets: sub-klient-uninstall_subtargets-ordered sub-serwer-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

